#!/bin/bash
#-*- coding: utf-8 -*-
#================================================================
#				AKILA SCRIPT INSTALL - ELEMENTARY OS
# Akila-eOS exclusivamente para elementary os, instalado pacotes 
# extras para elementary.
# Version: 1.0
# Author: Walber Vaz
# GitHub: https://github.com/walber-silva/akila-eos
# -> Conheça nosso outro projeto para Ubuntu e seus derivados
# GitHub: https://github.com/walber-silva/akila-script
#================================================================
clear
#VERIFICAÇÃO ROOT {{{
select_root(){
	if [[ ! $(whoami) = "root" ]]; then
		echo "********************************************************************************"
    	echo "OPS!VOCÊ TEM QUE EXECUTAR SCRIPT COMO ROOT"
		echo "********************************************************************************"
    	exit 1
	fi
}
#}}}
#FUNÇÃO PARA GERA OPÇÃO ESCOLHIDA PELO USUARIO {{{
#select_op(){

#}
#}}}
#TELA DE OPÇÕES PARA USUARIO {{{
tela_opcoes(){
	echo "================================================================================"
	echo "AKILA eOS - EXCLUSIVO PARA ELEMENTARY OS ¯\_(ツ)_/¯"
	echo "================================================================================"
	echo "[1]CODEC EXTRAS				[19]ATOM EDITOR DE TEXTO"
	echo "[2]PROGRAMAS EXTRAS(p7zip, rar..etc)	[20]BRACKETS EDITOR DE TEXTO"
	echo "[3]FIREFOX				[21]SUBLIME TEXT EDITOR DE TEXTO"
	echo "[4]GDEBI(INSTALADOR ARQUIVOS .deb)	[22]JAVA(ORACLE)"
	echo "[5]UBUNTU TWEAK				[23]OPENJDK(JAVA)"
	echo "[6]UNETBOOTIN				[24]THUNDERBIRD"
	echo "[7]ATUALIZAR SISTEMA			[25]ELEMENTARY TWEAKS"
	echo "[8]REMOVE PACOTES			[26]GCC(COMPILADOR)"
	echo "[9]INSTALAR LIBREOFFICE 		[27]INKSCAPE"
	echo "[10]NUMIX ICON				[28]GPARTED"
	echo "[11]EL FAENZA ICON 			[29]TRANSMISSION"
	echo "[12]NUMIX UTOUCH ICON 			[30]GUFW(FIREWALL)"
	echo "[13]TAP ICON 				[31]MONITORAMENTO DO SYSTEMA"
	echo "[14]MOKA ICON 				[32]DEIXANDO eOS EM PT-BR"
	echo "[15]WINE 				[33]FONTES EXTRAS"
	echo "[16]SIMPLESCREENRECORDER 		[34]BLENDER"
	echo "[18]ULTILIDARIO DE PARTIÇÕES 		[35]GIMP"
	echo "					[36]SAIR"
	echo "================================================================================"
	read -p "DIGITE [1 a 36] -> " op
	echo
}
#}}}
#CHAMANDO TODAS AS FUNÇÔES {{{
select_root
tela_opcoes
select_op
#}}}
